export const FETCH_PRODUCT_LIST = 'FETCH_PRODUCT_LIST';
export const PRODUCT_PENDING = 'PRODUCT_PENDING';
export const PRODUCT_REJECT = 'PRODUCT_REJECT';
export const FETCH_ADD_CHART = 'FETCH_ADD_CHART';
export const ADD_CHART_PENDING = 'ADD_CHART_PENDING';
export const ADD_CHART_REJECT = 'ADD_CHART_REJECT';
