export const HOME="Anasayfa"
export const PROFILE="Profile"
export const NOTTIFICATION="Bildirimler"
export const FAVORITES="Favoriler"
export const PRODUCTLIST="Ürünler"
export const TAB="TAB"
export const CART="Sepetim"